### ISSUE TITLE
SQLIteMap seems to work

### ISSUE THREAD

**Issue by sckott** [ropensci/spsqlite#2]
https://cran.rstudio.com/src/contrib/Archive/SQLiteMap/

Installed this from lastest version in archive, run examples and seems to work. 

The files in `/src` seem to be identical, BUT that pkg has a few `configure` scripts, which we don't have. perhaps that's the difference.

**Comment by sckott** [comment]
@Martin-Jung forgot to ping you above

**Comment by Martin-Jung** [comment]
Aye, will take a look soon. 
Cool would be to link the package dynamically against any local installed libs if available. No idea how to achieve this though.  Not to mention that it would be really awesome to link librasterlite (https://www.gaia-gis.it/fossil/librasterlite/index) to the package as well (sth. that is not yet possible in R)
Needs some C skill0rz.

**Comment by sckott** [comment]
Also curious why the author pulled that pkg from CRAN

**Comment by richfitz** [comment]
> Archived on 2012-09-30 after the package has been orphaned on 2012-09-19 as requested by the original maintainer, Norbert Solymosi <solymosi.norbert at gmail.com>

Looks like the author requested _orphan_ the package (i.e., drop maintenance), and then it was subsequently archived.  Orphaned packages can be adopted by anyone so if it's a useful starting off point / package name you could pick it up.

**Comment by Martin-Jung** [comment]
Other than SQLiteMap there is also this one here, which ships without configure scripts and works for me?
https://github.com/pschmied/RSQLite.spatialite
But it would be nice to build up on some work already done by SQLiteMap

**Comment by Martin-Jung** [comment]
Orphaned the original package, copy-pasted the configure scripts (they work just like that. Maybe someone wants to edit their comments / copyrights?).
Also improved the Init script so that the library is loaded anyway in case dynamic lookup after loading fails...

Result: 
Loads for me. Can be tested with the "testing.R"  script. Happy sunday!

**Comment by sckott** [comment]
@richfitz right, totally missed that about orphaned, mind skipped over it.
